### ISSUE TITLE
Implement into unoffical GPM desktop player

### ISSUE THREAD

**Issue by outpoints** [antigravities/Discrobble#1]
Do you think you could incorporate this into the desktop player app?
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

**Comment by outpoints** [comment]
Or make an app that does this?

**Comment by antigravities** [comment]
You may be able to patch my script into there somewhere, but unfortunately I don't use that app and haven't heard of it before now so I really wouldn't know. Sorry.
